# PCA Demo - Principal Component Analysis 

In [4]:
import numpy as np

In [5]:
# A = np.array([[1,0, 2], [1, 3, .5], [0, 1, 7]])
A = np.array([[1,-4, -2], [1, 3, -5], [-2, 1, 7]])
# A = np.array([[9,-3, 1], [4, 0, 0], [0, 1, 0]])
print(A, '\n')
print(f"rank = {np.linalg.matrix_rank(A)}\n")

print(f"A@A^T = {A @ np.transpose(A)}")

[[ 1 -4 -2]
 [ 1  3 -5]
 [-2  1  7]] 

rank = 2

A@A^T = [[ 21  -1 -20]
 [ -1  35 -34]
 [-20 -34  54]]


In [6]:
X = A
print(f"X = {X}")

# mean of each feature across all samples
Xbar = np.mean(X, axis=1, keepdims=True) 
print(f"Xbar = {Xbar}")

B = X - Xbar
print(f"B = {B}")

X = [[ 1 -4 -2]
 [ 1  3 -5]
 [-2  1  7]]
Xbar = [[-1.66666667]
 [-0.33333333]
 [ 2.        ]]
B = [[ 2.66666667 -2.33333333 -0.33333333]
 [ 1.33333333  3.33333333 -4.66666667]
 [-4.         -1.          5.        ]]


In [7]:
principalValues, W = np.linalg.eig(np.transpose(B) @ B)
index = np.argsort(principalValues)[::-1]
principalValues = principalValues[index]  # sort eigenvalues
W = W[:, index]  # sort eigenvectors

print(f"principalValues = \n{principalValues}")
print(f"W = {W}")

principalValues = 
[7.11073760e+01 1.82259573e+01 2.43087903e-15]
W = [[-0.49079864 -0.65252078  0.57735027]
 [-0.31970025  0.75130448  0.57735027]
 [ 0.81049889 -0.0987837   0.57735027]]


In [8]:
## I think this is right:
X = A
print(f"X = {X}")

# mean of each feature across all samples
Xbar = np.mean(X, axis=0, keepdims=True)     
print(f"Xbar = {Xbar}")

B = X - Xbar
print(f"B = {B}")

np.round(np.transpose(W) @ W, 5)

X = [[ 1 -4 -2]
 [ 1  3 -5]
 [-2  1  7]]
Xbar = [[0. 0. 0.]]
B = [[ 1. -4. -2.]
 [ 1.  3. -5.]
 [-2.  1.  7.]]


array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [9]:
principalValues, W = np.linalg.eig(np.transpose(B) @ B)
index = np.argsort(principalValues)[::-1]
principalValues = principalValues[index]  # sort eigenvalues
W = W[:, index]  # sort eigenvectors

print(f"principalValues = \n{principalValues}")
print(f"W = {W}")

principalValues = 
[ 8.36879766e+01  2.63120234e+01 -6.66133815e-15]
W = [[ 0.26141172  0.10335852 -0.95967751]
 [-0.01359443 -0.99375732 -0.11073202]
 [-0.96513165  0.04199292 -0.25837471]]


In [10]:
np.round(np.transpose(W) @ W, 5)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])