In [105]:
import numpy as np

In [106]:
# A = np.matrix([[1,0, 2], [1, 3, .5], [0, 1, 7]])
A = np.matrix([[1,-4, -2], [1, 3, -5], [-2, 1, 7]])
# A = np.matrix([[9,-3, 1], [4, 0, 0], [0, 1, 0]])
print(A, '\n')
print(f"rank = {np.linalg.matrix_rank(A)}\n")

print(f"A@A^T = {A @ np.transpose(A)}")

[[ 1 -4 -2]
 [ 1  3 -5]
 [-2  1  7]] 

rank = 2

A@A^T = [[ 21  -1 -20]
 [ -1  35 -34]
 [-20 -34  54]]


In [107]:

eigenvaluesU, U = np.linalg.eig(A @ np.transpose(A))
eigenvaluesU[np.abs(eigenvaluesU) < 1e-10] = 0.

print(f"U = \n{U}\neigenvalues = \n{eigenvaluesU}")
index = np.argsort(eigenvaluesU)[::-1]
eigenvaluesU = eigenvaluesU[index]  # sort eigenvalues
U = U[:, index]                     # sort eigenvectors

print(f"\nU sorted:\n{U}")
print(f"eigenvalues = \n{eigenvaluesU}")

U = 
[[-0.24552087  0.77870801 -0.57735027]
 [-0.55162048 -0.60198132 -0.57735027]
 [ 0.79714136 -0.17672669 -0.57735027]]
eigenvalues = 
[83.68797658 26.31202342  0.        ]

U sorted:
[[-0.24552087  0.77870801 -0.57735027]
 [-0.55162048 -0.60198132 -0.57735027]
 [ 0.79714136 -0.17672669 -0.57735027]]
eigenvalues = 
[83.68797658 26.31202342  0.        ]


In [118]:
eigenvaluesV, V = np.linalg.eig(np.transpose(A) @ A)
# eigenvaluesV[np.abs(eigenvaluesV) < 1e-10] = 0.

index = np.argsort(eigenvaluesV)[::-1]
eigenvaluesV = eigenvaluesV[index]  # sort eigenvalues
V = V[:, index]  # sort eigenvectors  

print(f"\nV sorted:\n{V}")
print(f"Eigenvalues:\n{eigenvaluesV}")


V sorted:
[[ 0.26141172  0.10335852 -0.95967751]
 [-0.01359443 -0.99375732 -0.11073202]
 [-0.96513165  0.04199292 -0.25837471]]
Eigenvalues:
[ 8.36879766e+01  2.63120234e+01 -6.66133815e-15]


In [109]:
S = np.zeros((len(U), len(V)))
for i in range(min(len(U), len(V))):
    S[i, i] = np.sqrt(eigenvaluesU[i]) 

# correction to make U and V consistent
SCorrected = np.transpose(U) @ A @ V
for i in range(min(len(U), len(V))):
    V[:, i] = V[:, i] * np.sign(SCorrected[i, i])

In [110]:
sZeroed = SCorrected 
sZeroed[np.abs(sZeroed) < 1e-10 ] = 0
print(f"S:\n{S} \nScorrected, zeroed:\n{sZeroed}")

S:
[[9.14811328 0.         0.        ]
 [0.         5.12952468 0.        ]
 [0.         0.         0.        ]] 
Scorrected, zeroed:
[[-9.14811328  0.          0.        ]
 [ 0.          5.12952468  0.        ]
 [ 0.          0.          0.        ]]


In [111]:
np.round(U*S*np.transpose(V), 6)

array([[ 1., -4., -2.],
       [ 1.,  3., -5.],
       [-2.,  1.,  7.]])

In [112]:
error = A - U*S*np.transpose(V)
print(f"error less than 1e-10: {np.allclose(error, np.zeros_like(error), 1e-10)}")

error less than 1e-10: True
